# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramazan/cpp-course/Huffman-zip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramazan/cpp-course/Huffman-zip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramazan/cpp-course/Huffman-zip/CMakeFiles /home/ramazan/cpp-course/Huffman-zip/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramazan/cpp-course/Huffman-zip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named huflib

# Build rule for target.
huflib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 huflib
.PHONY : huflib

# fast build rule for target.
huflib/fast:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/build
.PHONY : huflib/fast

compress_testing.o: compress_testing.cpp.o

.PHONY : compress_testing.o

# target to build an object file
compress_testing.cpp.o:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/compress_testing.cpp.o
.PHONY : compress_testing.cpp.o

compress_testing.i: compress_testing.cpp.i

.PHONY : compress_testing.i

# target to preprocess a source file
compress_testing.cpp.i:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/compress_testing.cpp.i
.PHONY : compress_testing.cpp.i

compress_testing.s: compress_testing.cpp.s

.PHONY : compress_testing.s

# target to generate assembly for a file
compress_testing.cpp.s:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/compress_testing.cpp.s
.PHONY : compress_testing.cpp.s

lib/codes.o: lib/codes.cpp.o

.PHONY : lib/codes.o

# target to build an object file
lib/codes.cpp.o:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/lib/codes.cpp.o
.PHONY : lib/codes.cpp.o

lib/codes.i: lib/codes.cpp.i

.PHONY : lib/codes.i

# target to preprocess a source file
lib/codes.cpp.i:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/lib/codes.cpp.i
.PHONY : lib/codes.cpp.i

lib/codes.s: lib/codes.cpp.s

.PHONY : lib/codes.s

# target to generate assembly for a file
lib/codes.cpp.s:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/lib/codes.cpp.s
.PHONY : lib/codes.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/main.cpp.s
.PHONY : main.cpp.s

utility/file_compressor.o: utility/file_compressor.cpp.o

.PHONY : utility/file_compressor.o

# target to build an object file
utility/file_compressor.cpp.o:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_compressor.cpp.o
.PHONY : utility/file_compressor.cpp.o

utility/file_compressor.i: utility/file_compressor.cpp.i

.PHONY : utility/file_compressor.i

# target to preprocess a source file
utility/file_compressor.cpp.i:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_compressor.cpp.i
.PHONY : utility/file_compressor.cpp.i

utility/file_compressor.s: utility/file_compressor.cpp.s

.PHONY : utility/file_compressor.s

# target to generate assembly for a file
utility/file_compressor.cpp.s:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_compressor.cpp.s
.PHONY : utility/file_compressor.cpp.s

utility/file_decompressor.o: utility/file_decompressor.cpp.o

.PHONY : utility/file_decompressor.o

# target to build an object file
utility/file_decompressor.cpp.o:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_decompressor.cpp.o
.PHONY : utility/file_decompressor.cpp.o

utility/file_decompressor.i: utility/file_decompressor.cpp.i

.PHONY : utility/file_decompressor.i

# target to preprocess a source file
utility/file_decompressor.cpp.i:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_decompressor.cpp.i
.PHONY : utility/file_decompressor.cpp.i

utility/file_decompressor.s: utility/file_decompressor.cpp.s

.PHONY : utility/file_decompressor.s

# target to generate assembly for a file
utility/file_decompressor.cpp.s:
	$(MAKE) -f CMakeFiles/huflib.dir/build.make CMakeFiles/huflib.dir/utility/file_decompressor.cpp.s
.PHONY : utility/file_decompressor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... huflib"
	@echo "... edit_cache"
	@echo "... compress_testing.o"
	@echo "... compress_testing.i"
	@echo "... compress_testing.s"
	@echo "... lib/codes.o"
	@echo "... lib/codes.i"
	@echo "... lib/codes.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utility/file_compressor.o"
	@echo "... utility/file_compressor.i"
	@echo "... utility/file_compressor.s"
	@echo "... utility/file_decompressor.o"
	@echo "... utility/file_decompressor.i"
	@echo "... utility/file_decompressor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

